//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProtocolException.java
//  @ Date : 10/9/2013
//  @ Author : 
//
//



package com.eyecall.connection;


public class ProtocolException {
}
