//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HelpActivity.java
//  @ Date : 10/9/2013
//  @ Author : 
//
//



package com.eyecall.vip;


public class HelpActivity extends Activity  {
    private Object connection Connection;
}
