//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MainActivity.java
//  @ Date : 10/9/2013
//  @ Author : 
//
//



package com.eyecall.vip;

import android.app.Activity;


public class MainActivity extends Activity {
}
