//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VIPProtocolHandler.java
//  @ Date : 10/9/2013
//  @ Author : 
//
//



package com.eyecall.vip;


public class VIPProtocolHandler implements com.eyecall.connection.ProtocolHandler {
    public void State handleMessage(Object State, Object String, Object Map<String, Object Object>);
}
