//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Connection.java
//  @ Date : 10/9/2013
//  @ Author : 
//
//



package com.eyecall.connection;


private class Connection {
    private ProtocolHandler handler;
    private State state;
}
