//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProtocolHandler.java
//  @ Date : 10/9/2013
//  @ Author : 
//
//



package com.eyecall.connection;


public interface ProtocolHandler {
    public void State handleMessage(Object State, Object String, Object Map<String, Object Object>);
}
