//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LocationsActivity.java
//  @ Date : 10/9/2013
//  @ Author : 
//
//



package com.eyecall.volunteer;


public class LocationsActivity {
    private com.eyecall.connection.Connection connection;
}
