//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AudioBuffer.java
//  @ Date : 10/9/2013
//  @ Author : 
//
//



package com.eyecall.android;


public class AudioBuffer {
}
