//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VideoBuffer.java
//  @ Date : 10/9/2013
//  @ Author : 
//
//



package com.eyecall.android;


public class VideoBuffer {
}
