//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Request.java
//  @ Date : 10/9/2013
//  @ Author : 
//
//



package com.eyecall.server;


public class Request {
    private VIP vip;
    private Volunteer volunteer;
    private List<Volunteer> potentialVolunteers;
}
