//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Server.java
//  @ Date : 10/9/2013
//  @ Author : 
//
//



package com.eyecall.server;


public class Server {
    private List<Request> requests;
}
