//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ServerProtocolHandler.java
//  @ Date : 10/9/2013
//  @ Author : 
//
//



package com.eyecall.server;


public class ServerProtocolHandler implements com.eyecall.connection.ProtocolHandler {
    private Request request;
    public void State handleMessage(Object State, Object String, Object Map<String, Object Object>);
    
    public class QueryHandler {
    }
}
