//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VIP.java
//  @ Date : 10/9/2013
//  @ Author : 
//
//



package com.eyecall.server;


public class VIP {
    private com.eyecall.connection.Connection connection;
}
